### ISSUE TITLE
BWA samXe error

### ISSUE THREAD

**Issue by rnerell** [biointec/halvade#10]
Hi, 
I am doing DNA sequence and facing BWA samXe. Steps I performed include,
Preprocessed input files and stored onto HDFS. 
Prepared the reference data by following the manual. 
And my config looks like this,
N=40
M=190
C=12
B="/user/rnerell/halvade/bin.tar.gz"
D="/user/rnerell/halvade/ref_newgatk/dbsnp/dbsnp_138.hg19.vcf""
R="/user/rnerell/halvade/ref/ucsc.hg19"
I="/user/rnerell/halvade/in_1/"
O="/user/rnerell/halvade/out_newgatk/"

FYI, I am using latest GATK file(3.8) in this run. 
I have tried using custom arguments CA="bwa_sampe" as well. 

[halvade29891.stderr.zip](https://github.com/biointec/halvade/files/1381289/halvade29891.stderr.zip)
I am attaching the log for you to verify. Please let me know if I am missing something.

**Comment by ddcap** [comment]
Hi,

I'll have a look at it, it doesn't seem to be a GATK related issue as it fails in the map phase where it only uses bwa. Also by default it runs bwa mem now instead of bwa aln and sampe. I'll keep you updated.

best,
Dries

**Comment by ddcap** [comment]
Hi,

You certainly shouldn’t have to add custom arguments for bwa aln, also they work like this:
CA=“bwa_aln=arg1 arg2”.
Could you give me the stderr files of one of the failed tasks so I can see what goes wrong. It should start bwa mem but somehow ends up with the bwa aln instance class.
Also are you using the latest version?

Best,
Dries

**Comment by rnerell** [comment]
Hi Dries,

Please have a look at my stderr from the attachment. I pulled it couple of
months back.
But I am using a latest GATK (3.8).

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu,

Yes I've seen that log, but that is the log of the Hadoop command itself, you also have log files of every task  that ran. This is typically stored on the HDFS or which ever distributed filesystem you used. This will give information as to what is going wrong.
Also if you ran a couple of months ago you are probably working with an older version, and I changed some things in the last version to work with GATK 3.8. Could you try to run it with the latest version?

best,
Dries

**Comment by rnerell** [comment]
Hi Dries,

My bad, I have attached the log from HDFS. Sure thing, I will get the
latest pull and try it again.
Thanks Dries. I appreciate.

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu,
Any results yet? Also I don't see the logs you have attached, could you give a link to the logs?

**Comment by rnerell** [comment]
Hi Dries,

I attached logs in my last email. Over the weekend i took a latest pull
from git and tried it out. But, stuck with Mark duplicate issue.
So, I added CA args 'CA=”picard_markduplicates”' but no luck. With this
email I am attaching log files for both the runs.
Let me know if you don't receive the attachments.

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu,
I'm not getting any attachments, I think they don't work when you add them to the email. Perhaps you could give a link like you did the first stderr file you showed me? 
The CA arguments isn't to enable to markduplicates command but its to modifiy the command, like add parameters, so you shouldn't use it unless you really need the extra parameters.
Dries

**Comment by rnerell** [comment]
Alright!! I have uploaded log files to my drive, please get the log files
from below link.

https://drive.google.com/open?id=0B5kQSstBUxc8TXRhRVRqWF9tWGc

To access the link from stderr file you need to have a VPN connection to
connect to the cluster of my university. However, this should solve the
problem.

Thanks
ramu

**Comment by ddcap** [comment]
The logs show the contents of a directory. The logs that show information are the logs of the map and reduce tasks of the mapreduce application. These can be accessed through the web interface of Hadoop when you click on the application and then on a failed task from that application. 
They should be in a folder called userlogs defined by  ${yarn.nodemanager.log-dirs} .
best, Dries

**Comment by rnerell** [comment]
Hi Dries,

The log files which I sent you earlier contains directory info. Now, I got
the all available logs from the server for the latest run.
Please get the logs from below link,

https://drive.google.com/open?id=0B5kQSstBUxc8TXRhRVRqWF9tWGc

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu, 
This also doesn't contain the task logs. What I'm looking for is a stderr and stdout of one of the failed tasks, so there's a couple of hundred of tasks, and each of these tasks has a stderr and stdout file. If you could give me them of one of the tasks that failed that would help me find the problem.
best,
Dries

**Comment by rnerell** [comment]
Hi Dries,

I hope this will help.

https://drive.google.com/open?id=0B5kQSstBUxc8TXRhRVRqWF9tWGc

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu,
Yes these were the files I'm looking for, it seems you have a very very small sample, only 10 records in a region, this could be the problem.
How big is your input data?

**Comment by rnerell** [comment]
Hi Dries,

There are 16 i/p files and the total size is little less than gb
combined(0.76 GB).

thanks
ramu

**Comment by ddcap** [comment]
Hi Ramu,
I think that might be a problem. That really is a small amount of data, you also can't do reliable variant calling with only this amount of data. Try to use a whole genome or whole exome sample and see if that works.

**Comment by rnerell** [comment]
Hi Dries,

Thanks for your input. I started working with full dataset. Now, I am
facing a different issue.
Please find the issue details from the below link,
https://drive.google.com/open?id=0B5kQSstBUxc8TXRhRVRqWF9tWGc

Best
Ramu

**Comment by ddcap** [comment]
Hi Ramu, It seems that it takes 'null' as the reference file, so it didn't find this file. Could you show me the arguments you used with Halvade?

**Comment by rnerell** [comment]
Hi,
Please have a look at my arguments.

https://drive.google.com/open?id=0B5kQSstBUxc8TXRhRVRqWF9tWGc

Best
Ramu

**Comment by ddcap** [comment]
You gave a link to the picture you showed me before of the stderr log, not of the arguments.

**Comment by rnerell** [comment]
Please check now.

https://drive.google.com/open?id=0B5kQSstBUxc8UnpTR01Mb3NjTWM

**Comment by ddcap** [comment]
I think the problem is that on one of the nodes the download of the reference file was interrupted while testing (Hadoop job canceled without finishing), and left an invalid reference on that node. I have had this error before, and you can fix it by deleting the tmp directory on every node (/tmp/halvade) and run the program again, it should now correctly download the reference files.
Let me know if it works now.

**Comment by rnerell** [comment]
Hi Dries,

Thanks for your help, I followed your instructions.
My map tasks ran perfectly, but the reducers failed with "

process ended with 1
Picard MarkDuplicates exited with code 1

" issue. I am attaching the logs in the below link, please have a look.

https://drive.google.com/open?id=1F5KPuXd3yy8DyO57oN3wE0tcd0AKSzk4

P.S: I am using the whole dataset here.(~10 gb)

Best
Ramu

**Comment by ddcap** [comment]
I see that you still are using the old bin.tar.gz file, I recently updated some tool versions that I use with Halvade and Picard is one of them. Instead of using separate jar files for all tools it is now all included into one picard.jar file. But this file isn't in your bin.tar.gz file.
So you can either add this file from the picard site to your bin.tar.gz or download the latest version of Halvade and use that bin.tar.gz (note that you will need to add GATK again).

Let me know if this fixes things.

**Comment by rnerell** [comment]
Hi Dries,

The job ran successfully. Thanks for your help.
I really appreciate.

Best
Ramu
