### ISSUE TITLE
Haplotypecaller is not defined in the options. 

### ISSUE THREAD

**Issue by rnerell** [biointec/halvade#11]
I am trying to use Haplotypecaller variant calling tool from GATK. But, when I enabled this option I am getting Unrecognized option issue. I have looked into HalvadeOptions.java and I couldn't find any declaration for this option.

**Comment by ddcap** [comment]
The latest version of Halvade runs Haplotypecaller automatically. So the option has been changed to unifiedgenotyper if you want to run the pipeline with this variant caller.
So just remove this option and it should run with haplotypecaller,I will change the documentation as soon as possible to reflect this.

**Comment by rnerell** [comment]
Thanks for the info.
