### ISSUE TITLE
Running Halvade on other species

### ISSUE THREAD

**Issue by evcon131** [biointec/halvade#14]
Is it possible to run Halvade on other species? Say dog for example.

**Comment by ddcap** [comment]
Yes, simply use the dog fasta reference to create the bwa index instead of the human fasta reference. Similarly use a corresponding known sites for dogs vcf file and the rest should be the same.

**Comment by ddcap** [comment]
If no dbsnp is available for the species (dog) you can skip the bqsr step with the `--skip_bqsr` option of Halvade.

**Comment by evcon131** [comment]
Ah ok perfect I was just going to ask about that thanks!
