### ISSUE TITLE
Unable to compile halvade_upload_tool

### ISSUE THREAD

**Issue by linhbngo** [biointec/halvade#2]
Hi, 

When I run ant inside halvade_upload_tool, I receive the following errors:
# 

-do-compile:
    [javac] Compiling 24 source files to /home/lngo/git/halvade/halvade_upload_tool/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/HalvadeUploader.java:48: error: package org.seqdoop.hadoop_bam does not exist
    [javac] import org.seqdoop.hadoop_bam.BAMInputFormat;
    [javac]                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/HalvadeUploader.java:49: error: package org.seqdoop.hadoop_bam does not exist
    [javac] import org.seqdoop.hadoop_bam.FastqOutputFormat;
    [javac]                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/HalvadeUploader.java:50: error: package org.seqdoop.hadoop_bam does not exist
    [javac] import org.seqdoop.hadoop_bam.SequencedFragment;
    [javac]                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/BamRecordMapper.java:8: error: package htsjdk.samtools does not exist
    [javac] import htsjdk.samtools.SAMRecord;
    [javac]                       ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/BamRecordMapper.java:12: error: package org.seqdoop.hadoop_bam does not exist
    [javac] import org.seqdoop.hadoop_bam.SAMRecordWritable;
    [javac]                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/BamRecordMapper.java:18: error: cannot find symbol
    [javac] public class BamRecordMapper extends Mapper<LongWritable, SAMRecordWritable, PairedIdWritable, FastqRecord> {
    [javac]                                                           ^
    [javac]   symbol: class SAMRecordWritable
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/BamRecordMapper.java:24: error: cannot find symbol
    [javac]     protected void map(LongWritable key, SAMRecordWritable value, Context context) throws IOException, InterruptedException {
    [javac]                                          ^
    [javac]   symbol:   class SAMRecordWritable
    [javac]   location: class BamRecordMapper
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:14: error: package org.seqdoop.hadoop_bam does not exist
    [javac] import org.seqdoop.hadoop_bam.SequencedFragment;
    [javac]                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:19: error: package org.seqdoop.hadoop_bam.FormatConstants does not exist
    [javac] import org.seqdoop.hadoop_bam.FormatConstants.BaseQualityEncoding;
    [javac]                                              ^
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:51: error: cannot find symbol
    [javac]         protected BaseQualityEncoding baseQualityFormat;
    [javac]                   ^
    [javac]   symbol:   class BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:53: error: cannot find symbol
    [javac]         protected SequencedFragment seq = new SequencedFragment();
    [javac]                   ^
    [javac]   symbol:   class SequencedFragment
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/HalvadeUploader.java:124: error: cannot find symbol
    [javac]         FastqOutputFormat.setCompressOutput(job, true);
    [javac]         ^
    [javac]   symbol:   variable FastqOutputFormat
    [javac]   location: class HalvadeUploader
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/HalvadeUploader.java:129: error: cannot find symbol
    [javac]         job.setInputFormatClass(BAMInputFormat.class);
    [javac]                                 ^
    [javac]   symbol:   class BAMInputFormat
    [javac]   location: class HalvadeUploader
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/BamRecordMapper.java:25: error: cannot find symbol
    [javac]         SAMRecord sam = value.get();
    [javac]         ^
    [javac]   symbol:   class SAMRecord
    [javac]   location: class BamRecordMapper
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:53: error: cannot find symbol
    [javac]         protected SequencedFragment seq = new SequencedFragment();
    [javac]                                               ^
    [javac]   symbol:   class SequencedFragment
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:65: error: cannot find symbol
    [javac]                 baseQualityFormat = BaseQualityEncoding.Illumina;
    [javac]                                     ^
    [javac]   symbol:   variable BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:67: error: cannot find symbol
    [javac]                 baseQualityFormat = BaseQualityEncoding.Sanger;
    [javac]                                     ^
    [javac]   symbol:   variable BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:95: error: cannot find symbol
    [javac]             if (baseQualityFormat == BaseQualityEncoding.Sanger) {
    [javac]                                      ^
    [javac]   symbol:   variable BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:97: error: cannot find symbol
    [javac]             } else if (baseQualityFormat == BaseQualityEncoding.Illumina) {
    [javac]                                             ^
    [javac]   symbol:   variable BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:99: error: cannot find symbol
    [javac]                 SequencedFragment.convertQuality(buffer, BaseQualityEncoding.Sanger, baseQualityFormat);
    [javac]                                                          ^
    [javac]   symbol:   variable BaseQualityEncoding
    [javac]   location: class FastqRecordWriter
    [javac] /home/lngo/git/halvade/halvade_upload_tool/src/be/ugent/intec/halvade/uploader/mapreduce/MyFastqOutputFormat.java:99: error: cannot find symbol
    [javac]                 SequencedFragment.convertQuality(buffer, BaseQualityEncoding.Sanger, baseQualityFormat);
    [javac]                 ^
    [javac]   symbol:   variable SequencedFragment
    [javac]   location: class FastqRecordWriter
    [javac] 21 errors
    [javac] 1 warning

BUILD FAILED
/home/lngo/git/halvade/halvade_upload_tool/nbproject/build-impl.xml:920: The following error occurred while executing this line:
/home/lngo/git/halvade/halvade_upload_tool/nbproject/build-impl.xml:260: Compile failed; see the compiler error output for details.
# 

This does not happen with the halvade_upload_tool from the ddcap halvade repository

Thanks,

**Comment by ddcap** [comment]
Yes I'm getting the same problem, I will look into it thanks.

**Comment by ddcap** [comment]
I have updated the ant build files and for me it works now, let me know if it works for you as well.

best,
Dries

**Comment by linhbngo** [comment]
This works after I pull the latest update from the repository, thanks!
