### ISSUE TITLE
Loading multiple pairs of fastq files in one halvade run

### ISSUE THREAD

**Issue by linhbngo** [biointec/halvade#5]
Is it possible for HalvadeUploader to process multiple pairs of fastq files into a single halvade/in directory? I am asking this question for the case where we have multiple reads from multiple varieties of a species. All of these varieties will share the same set of reference files, and we wish to perform a comprehensive vcf process on the entire collection. 

Edit: I went back and read the documentation and the source code for HalvadeUpload. If I am to use multiple pairs, the manifest file will be under the following form:

pair1_file1.fastq    pair1_file2.fastq
pair2_file1.fastq    pair2_file2.fastq
....

Is this correct?

Thanks, 

Linh

**Comment by ddcap** [comment]
Yes, Indeed I was about to link you the documentation (http://halvade.readthedocs.io/en/latest/ just in case) and it should indeed be like that. Last time I used it, it was still working so let me know if it works for you. It will merge all fastq files together though so there is no distiniction anymore where they came from. If this should be the case then I advise to start a job for every fastq pair sepparately.

best,
Dries

**Comment by linhbngo** [comment]
From the way our scientist describes the workflow, the resulting .bam files from each variety are merged into a single .bam file using **samtools merge**, and the final variant call is performed on this merged file. 

To me, this looks to be very applicable to the merging capability of HalvadeUpload and Halvade workflow, with the only difference is when the merge happens. I will test this out and follow up on this. 

Thanks, 

Linh

**Comment by linhbngo** [comment]
In our setting, we have multiple fastq pairs. The resulting bams from each individual pair are merged at the end, but with the -r flag from samtools merge to keep track of the ReadGroup. I see several ReadGroup related flags within your documentation. It looks like a more correct approach to our case, as you suggested above, is to first run Halvade with the **--justalign** options for each individual pair. This would create a series of bam files. 

Next, we can run Halvade again with the bam files as input (**--bam**) for the remainder of the pipeline. In this case, how should the options related to ReadGroup be handled to ensure that the Group information are added? Or are these options to be done in the previous steps, specified for each individual pair alignment?

**Comment by ddcap** [comment]
It seems to be indeed like you suggested, to first indeed run first with --justalign to get the bam files for every readgroup and add the read group information in these runs with the options lb, sm, pl, pu, id (see http://halvade.readthedocs.io/en/latest/contents/options.html for what they mean). 
After this run merge the bam input files or run Halvade with the input pointing to the folder containing all the bam files with the --bam input, it should automatically read the readgroups you provided in the first runs. I haven't tried multiple bam inputs yet but it should work nonetheless. 
Let me know how it goes.

best,
Dries

**Comment by linhbngo** [comment]
The resulting bam files are sized around 5GB, and when I run the VCF phase, I have the following error:

2016-10-27 15:39:22,282 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: org.seqdoop.hadoop_bam.FileVirtualSplit@40bffbca
2016-10-27 15:39:22,938 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.OutOfMemoryError: Java heap space

As the Hadoop cluster we are running on is a shared cluster, it is not possible to set the global configuration of Hadoop. Do you know how I can include MapReduce configuration with the config file?

Thanks, 

Linh

**Comment by linhbngo** [comment]
Another related question, if merge-bam is not set, would the part-m-xxxxx output files for --justalignt are individual bam files in themselves or not?

**Comment by ddcap** [comment]
No the files would contain the SAM-record entries of the htsjdk toolkit (the developers of Samtools). Every line should contain one entry, but I'm not sure if this is a valid SAM entry or if its a serialized format.
I think you can modify the runHalvade.py script to include the MapReduce parameters something like this:
'-D mapred.mapper.mystring=somexyz'

best,
Dries

**Comment by linhbngo** [comment]
Dries, 

I have adjusted both mapreduce.(map/reduce).memory.mb and mapreduce.(map/reduce).java.opts on our cluster to be higher than 10Gb, but the problem still persists. 

When I looked back at the job logs and comparing a successful HalvadeCombineVCF job and this stand-along VCF creation job using --bam, I notice a different in the setting of mapreduce.map.memory.mb (--mapmem). For the HalvadeCombineVCF, I see the following:

mapreduce.map.memory.mb 32768   job.xml ⬅ programatically
mapreduce.reduce.memory.mb  32768   job.xml ⬅ programatically

But on the --bam job with Java heap space, I see the following:
mapreduce.map.memory.mb 4096    job.xml ⬅ programatically
mapreduce.reduce.memory.mb  184320  job.xml ⬅ programatically

This does not make sense, as the configuration for the --bam job specifies both mapmem and redmem at 180
N=10
M=190
C=1
mapmem=180
redmem=180

and only redmem is read into the job. The value of 4096 does not match to any configuration that we set for our Hortonworks Hadoop cluster, and seems to be generated by the job itself. Do you know which specific code is responsible for calling the execution of the --bam job.

**Comment by linhbngo** [comment]
Digging a bit further into the source code, I observe that SplittingBAMIndexer of Hadoop-BAM, which is likely part of 

2016-10-31 12:51:13,235 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: org.seqdoop.hadoop_bam.FileVirtualSplit@40bffbca 

prior to the error:
2016-10-31 12:51:13,590 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.OutOfMemoryError: Java heap space

and SplittingBAMIndexer contains the following line of code:

public static final int DEFAULT_GRANULARITY = 4096;

```
public static void main(String[] args) {
    if (args.length <= 1) {
        System.out.println(
            "Usage: SplittingBAMIndexer GRANULARITY [BAM files...]\n\n"+

            "Writes, for each GRANULARITY alignments in a BAM file, its "+
            "virtual file offset\nas a big-endian 64-bit integer into "+
            "[filename].splitting-bai. The file is\nterminated by the BAM "+
            "file's length, in the same format.");
        return;
    }
```

Could this be the explanation for the 4096 value?

**Comment by ddcap** [comment]
Hadoop determines memory not only based on the input but also on the type of input. The argument you give is the total memory on a node and Halvade splits this up in the number of containers possible. These are the values from the source code (from HalvadeResourceManager.java):
 `protected static final int MEM_ALN = (int) (10*1024);
    protected static final int MEM_STAR_FULL = (int) (32*1024); // full star ref
    protected static final int MEM_STAR_SMALL = (int) (10*1024); // second pass smaller star ref
    protected static final int MEM_STAR_SHARED = (int) (6*1024); // set minimum if memory check is disabled
    protected static final int MEM_REF = (int) (6*1024); // 4g for hg fasta + java process + some spare
    protected static final int MEM_ELPREP = (int) (16*1024); // 16g for hg for 50x coverage
    protected static final int[][] RESOURCE_REQ = { 
        //mapmem, redmem
        {MEM_STAR_FULL,  MEM_STAR_FULL},     // RNA with shared memory pass1
        {MEM_STAR_SMALL,  MEM_ELPREP}, // RNA with shared memory pass2
        {MEM_ALN,   MEM_ELPREP}, // DNA
        {4*1024,    4*1024}   // combine
    };
int mmem = RESOURCE_REQ[BAMinput? 3 : type][0];
`
Since you use bam input in your job, the map phase is set to 4GB, you can try to adjust this value. 
Later in this java file I set the java memory for the containers based on the container memory (20% or 80% depending on the type of job). Since it isn't a combine job it will set this to 20% of 4GB and it might be worth increasing this since you read from bam.

Let me know if you find anything new.
best,
Dries

**Comment by linhbngo** [comment]
Hi Dries, 

Sorry it took so long to get back to you. I have adjusted the memory value of RESOURCE_REQ to 30GB (30 \* 1024), and the out of memory error went away, but I now am faced with a different issue. All the mapping processes complete successfully, but the reducing processes hang indefinitely and end up getting killed  (even after I extended the timeout to 20 hours). One example final reduce task log looks like this (there is no definite error message):

2016-11-02 13:44:41,421 INFO [fetcher#24] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: closeInMemoryFile -> map-output of size: 238496, inMemoryMapOutputs.size() -> 81, commitMemory -> 139750077, usedMemory ->273890265
2016-11-02 13:44:41,422 INFO [fetcher#24] org.apache.hadoop.mapreduce.task.reduce.ShuffleSchedulerImpl: xxxx.xxxx.xxxx.xxxx:13562 freed by fetcher#24 in 401ms
2016-11-02 13:44:41,745 INFO [fetcher#9] org.apache.hadoop.mapreduce.task.reduce.InMemoryMapOutput: Read 133901692 bytes from map-output for attempt_1478108104158_0001_m_000073_0
2016-11-02 13:44:41,746 INFO [fetcher#9] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: closeInMemoryFile -> map-output of size: 133901692, inMemoryMapOutputs.size() -> 82, commitMemory -> 139988573, usedMemory ->273890265
2016-11-02 13:44:41,746 INFO [fetcher#9] org.apache.hadoop.mapreduce.task.reduce.ShuffleSchedulerImpl: xxxx.xxxx.xxxx.xxxx:13562 freed by fetcher#9 in 885ms
2016-11-02 13:44:41,747 INFO [EventFetcher for fetching Map Completion Events] org.apache.hadoop.mapreduce.task.reduce.EventFetcher: EventFetcher is interrupted.. Returning
2016-11-02 13:44:41,756 INFO [main] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: finalMerge called with 82 in-memory map-outputs and 0 on-disk map-outputs
2016-11-02 13:44:41,791 INFO [main] org.apache.hadoop.mapred.Merger: Merging 82 sorted segments
2016-11-02 13:44:41,794 INFO [main] org.apache.hadoop.mapred.Merger: Down to the last merge-pass, with 82 segments left of total size: 273889020 bytes
2016-11-02 13:44:47,071 INFO [main] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: Merged 82 segments, 273890265 bytes to disk to satisfy reduce memory limit
2016-11-02 13:44:47,072 INFO [main] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: Merging 1 files, 140823224 bytes from disk
2016-11-02 13:44:47,074 INFO [main] org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl: Merging 0 segments, 0 bytes from memory into reduce
2016-11-02 13:44:47,074 INFO [main] org.apache.hadoop.mapred.Merger: Merging 1 sorted segments
2016-11-02 13:44:47,081 INFO [main] org.apache.hadoop.mapred.Merger: Down to the last merge-pass, with 1 segments left of total size: 273890088 bytes

I visually inspected all the failed reduce tasks, and they all produced log similar to the above, with various segment counts and total sizes. 

The command being run as reported in syserr is:

[2016/11/02 13:45:17 - DEBUG] running command [java, -Xmx147456m, -jar, ./bin.tar.gz/bin/MarkDuplicates.jar, INPUT=/tmp/halvade/attempt_1478108104158_0001_r_000000_0region_0-p1.bam, OUTPUT=/tmp/halvade/attempt_1478108104158_0001_r_000000_0region_0.bam, METRICS_FILE=/tmp/halvade/attempt_1478108104158_0001_r_000000_0region_0-p3-metrics.txt, VALIDATION_STRINGENCY=LENIENT, ASSUME_SORTED=true]

I did ps aux check on the nodes, and it seems like they all were waiting for something to happen (no CPU utilization on the java processes). Any thought/suggestion on what this means? My config file looks like this:

N=10
M=190
C=4
B="/user/lngo/halvade/bin.tar.gz"
R="/user/lngo/halvade/ref-files"
I="/user/lngo/halvade/inEMACE-merged-bams/"
O="/user/lngo/halvade/outEMACE-from-bams/"
mapmem=180
redmem=180
mpn=1
rpn=1
smt
skip_bqsr
snappy
combine
bam

Thanks, 

Linh

**Comment by linhbngo** [comment]
I found this, and now trying it out to see what happened, will keep you updated :)

Halvade with BAM input seems stuck at the MarkDuplicates step
 +-------------------------------------------------------------
 +If the stderr log of a reduce task shows it started the MarkDuplicates file but didn't finish in a considerable time. Then it is highly likely it is finding incorrect aligned reads and giving error messages that slow the process to the point where it seems stuck. If this is the case, look at the header file of the BAM file and the fasta dictionary file, if the contig order is different then this is the source of the problem. Halvade assigns the contig by index in the sequence dictionary when reading the bam files and this causes wrong matching between steps. To fix this, the sequence dictionary of the bam files needs to be reordered the same as the dict file. This can be done with the ReorderSam tool by Picard like this:
 +
 +.. code-block:: bash
-  :linenos:
  +
-  java -jar picard.jar ReorderSam I=input.bam O=output.bam R=reference.fasta
  +
  +Use the new file as input and Halvade should run without any problems now.

**Comment by linhbngo** [comment]
After running picard ReorderSam, I still have the Halvade application hanging at MarkDuplicates. Is there a way to enable further debugging (default = 2) to see if there is any error message?

**Comment by ddcap** [comment]
By default all debugging is on, (debugging 2), 1 shows left less debug. What I do when something is stuck and the logs don't show anything, is running the command manually where it gets stuck. In the log files of a task you can see the last command that is run, the files used should still be available if the job is killed. Run the command and see why it is stopping or not running. This usually leads me to find the problem of the input file or other reasons. This is also how I found the issue you referred to 2 comments ago, perhaps it is a similar but different problem. Let me know what you find.

**Comment by linhbngo** [comment]
With your suggestion, I run the **[java, -Xmx147456m, -jar, ./bin.tar.gz/bin/MarkDuplicates.jar,** command, and it turns out that for every single entry, the following error message appears: **"Ignoring SAM validation error: ERROR: Record xxxxx, Read name xxxxx, RG ID on on SAMRecord not found in header:".**

It seems that there is no common header to my bam file since it is a merge from several other BAM files and also retains all the different headers for each individual read line. I am looking at MarkDuplicates to see if it is possible to suppress the error message ...

**Comment by linhbngo** [comment]
Sorry for keeping this opened for so long. This error has been corrected via [closed issue 7](https://github.com/biointec/halvade/issues/7)
