### ISSUE TITLE
Could Halvade be installed on a SGE cluster without administrator permissions

### ISSUE THREAD

**Issue by YingYa** [biointec/halvade#6]
Could Halvade be installed on a SGE cluster without administrator permissions？

**Comment by ddcap** [comment]
As long as it can write to the files on the used filesystem (e.g. your home folder) and there is Hadoop MapReduce available, I believe so yes. In our cluster we use a hadoop system based on HadoopOnDemand (which was developed by ugent), as far as I know this is opensource and can thus be installed on your cluster as well. See here for more information: https://github.com/hpcugent/hanythingondemand.
