### ISSUE TITLE
GATK 3.7

### ISSUE THREAD

**Issue by linhbngo** [biointec/halvade#9]
Hi, 

With the new release of GATK 3.7 tool, could you provide some comments on whether halvade workflow would still work as intended?

More specifically, am I correct in saying that the Halvade workflow still matches the [current optimal pipeline for SNP calling](https://software.broadinstitute.org/gatk/best-practices/bp_3step.php?case=GermShortWGS&p=2)? This includes the new functionalities of the [HaplotypeCaller](https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller.php) tools and the [joint genotyping tool](https://software.broadinstitute.org/gatk/gatkdocs/3.5-0/org_broadinstitute_gatk_tools_walkers_variantutils_GenotypeGVCFs.php4)

Thanks, 

Linh

**Comment by linhbngo** [comment]
I see that you have GVCF supported in the code, but it is not shown in the documents yet.

**Comment by ddcap** [comment]
Indeed, Halvade provides the option to calculate gvcf files that can later be combined as described in the pipeline. I have not yet added this to the documentation as I haven't really tested this yet. It is on my to do list! And as far as I know, it should work without problems, but I'd still like to test it first before adding it to the documentation, but feel free to try it out as well!
You need to use the --haplotypecaller option to enable using the HaplotypeCaller and then --gvcf to use this option.
